# Generated by Django 4.0.3 on 2022-03-12 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('business_category', models.CharField(choices=[('Agency', 'Agency'), ('Ecommerce Business', 'Ecommerce Business'), ('Affiliate Marketing', 'Affiliate Marketing'), ('Tech Business', 'Tech Business'), ('Other', 'Other')], default='Agency', max_length=100)),
                ('phone', models.CharField(max_length=255)),
                ('website_url', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
