# Generated by Django 4.0.3 on 2022-04-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_manager_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Product Descriptions', 'Product Descriptions'), ('Blogs & Articles', 'Blogs & Articles'), ('Email Marketing', 'Email Marketing'), ('Ad Copy', 'Ad Copy'), ('Web Copy', 'Web Copy'), ('Video Scripts', 'Video Scripts')], max_length=255)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateField()),
                ('requirements', models.CharField(max_length=2000)),
                ('details', models.CharField(max_length=2000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.customer')),
            ],
        ),
    ]
