# Generated by Django 4.0.3 on 2022-06-08 21:26

import api.models.order
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_manager_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_category', models.CharField(choices=[('In Progress', 'In Progress'), ('Awaiting Brief', 'Awaiting Brief'), ('In Revision', 'In Revision'), ('Complete', 'Complete'), ('Refund', 'Refund'), ('Canceled', 'Canceled')], default='Awaiting Brief', max_length=100)),
                ('overall_status_category', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Active', max_length=100)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_description', to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('hint', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requirement', to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('service_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicedescription')),
                ('service_requirement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.servicerequirement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_image', models.ImageField(upload_to=api.models.order.user_directory_path)),
                ('service_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicedescription')),
                ('service_requirement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.servicerequirement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to=api.models.order.user_directory_path)),
                ('service_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicedescription')),
                ('service_requirement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.servicerequirement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=1000, null=True)),
                ('service_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.servicedescription')),
            ],
        ),
    ]
