# Generated by Django 4.0.3 on 2022-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='overall_status_category',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Active', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='status_category',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Awaiting Brief', 'Awaiting Brief'), ('In Revision', 'In Revision'), ('Complete', 'Complete'), ('Refund', 'Refund'), ('Canceled', 'Canceled')], default='Awaiting Brief', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='details',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='requirements',
            field=models.TextField(max_length=2000),
        ),
    ]
