# Generated by Django 4.0.3 on 2022-06-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_service_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedescription',
            old_name='details',
            new_name='text',
        ),
    ]
