# Generated by Django 4.0.3 on 2022-06-16 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_details_servicedescription_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='service_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='api.servicedescription'),
        ),
    ]
