# Generated by Django 4.0.3 on 2022-06-16 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_service_req_servicerequirement_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
