# Generated by Django 4.0.3 on 2022-06-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service', to='api.order'),
            preserve_default=False,
        ),
    ]
