# Generated by Django 4.0.3 on 2022-06-16 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_service_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service', to='api.order'),
        ),
    ]
