# Generated by Django 4.0.3 on 2022-06-16 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_service_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.service'),
        ),
    ]
