# Generated by Django 4.0.3 on 2022-06-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_order_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedescription',
            name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
