# Generated by Django 4.0.3 on 2022-06-17 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_servicedescription_title_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefield',
            name='service_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.servicedescription'),
        ),
        migrations.AlterField(
            model_name='filefield',
            name='service_requirement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.servicerequirement'),
        ),
        migrations.AlterField(
            model_name='imagefield',
            name='service_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.servicedescription'),
        ),
        migrations.AlterField(
            model_name='imagefield',
            name='service_requirement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.servicerequirement'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='service_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.servicedescription'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='service_requirement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.servicerequirement'),
        ),
    ]
