# Generated by Django 4.0.3 on 2022-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_filefield_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefield',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagefield',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='textfield',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
