# Generated by Django 4.0.3 on 2022-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_filefield_type_imagefield_type_textfield_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filefield',
            name='type',
        ),
        migrations.RemoveField(
            model_name='imagefield',
            name='type',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='type',
        ),
        migrations.AddField(
            model_name='servicerequirement',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
