# Generated by Django 4.0.3 on 2022-06-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_filefield_type_remove_imagefield_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefield',
            name='service_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.servicedescription'),
        ),
        migrations.AlterField(
            model_name='filefield',
            name='service_requirement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.servicerequirement'),
        ),
        migrations.AlterField(
            model_name='imagefield',
            name='service_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.servicedescription'),
        ),
        migrations.AlterField(
            model_name='imagefield',
            name='service_requirement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.servicerequirement'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='service_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.servicedescription'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='service_requirement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.servicerequirement'),
        ),
    ]
