# Generated by Django 4.0.3 on 2022-06-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_servicerequirement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequirement',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
