# Generated by Django 4.0.3 on 2022-07-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_servicerequirement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefield',
            name='upload_file',
            field=models.FileField(upload_to='store/files'),
        ),
        migrations.AlterField(
            model_name='imagefield',
            name='upload_image',
            field=models.ImageField(upload_to='store/images'),
        ),
    ]
