# Generated by Django 4.0.3 on 2022-07-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_filefield_upload_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequirement',
            old_name='hint',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='servicerequirement',
            name='details',
        ),
        migrations.RemoveField(
            model_name='servicerequirement',
            name='title',
        ),
    ]
