# Generated by Django 4.0.3 on 2022-07-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_filefield_upload_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefield',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='imagefield',
            name='service_requirement',
        ),
    ]
