# Generated by Django 4.0.3 on 2022-07-17 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_imagefield_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefield',
            name='service_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.servicedescription'),
        ),
        migrations.AddField(
            model_name='imagefield',
            name='service_requirement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.servicerequirement'),
        ),
    ]
