# Generated by Django 4.0.3 on 2022-07-17 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_imagefield_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefield',
            name='service_requirement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.servicerequirement'),
        ),
        migrations.AlterField(
            model_name='imagefield',
            name='service_requirement',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.servicerequirement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textfield',
            name='service_requirement',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='api.servicerequirement'),
            preserve_default=False,
        ),
    ]
