# Generated by Django 4.0.3 on 2022-07-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_filefield_service_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefield',
            name='service_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.servicedescription'),
        ),
        migrations.AlterField(
            model_name='filefield',
            name='service_requirement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.servicerequirement'),
        ),
        migrations.AlterField(
            model_name='imagefield',
            name='service_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.servicedescription'),
        ),
        migrations.AlterField(
            model_name='imagefield',
            name='service_requirement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.servicerequirement'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='service_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.servicedescription'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='service_requirement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.servicerequirement'),
        ),
    ]
