# Generated by Django 4.0.3 on 2022-07-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_filefield_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfield',
            name='service_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_field', to='api.servicedescription'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='service_requirement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_field', to='api.servicerequirement'),
        ),
    ]
