# Generated by Django 4.0.6 on 2022-07-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_order_service_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='src',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
