# Generated by Django 4.0.3 on 2022-07-25 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_service_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='service_description',
        ),
        migrations.AddField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='api.service'),
        ),
    ]
