# Generated by Django 4.0.3 on 2022-07-25 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_faq_service_description_faq_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_faq', to='api.service'),
        ),
    ]
