# Generated by Django 4.0.3 on 2022-07-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_faq_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service', to='api.order'),
        ),
    ]
